EmployeeInformation/EmpRecord/Postman_Hardik/urls.py
from django.urls import path 
from EmpRecord.views import *
# from EmpRecord import views
from .views import  EmployeeListView, EmployeeDetailView


app_name = 'EmployeeInformation'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('employee_list_test/', EmployeeListView, name='employee_list'),
    path('employee_list_test/<int:pk>/', EmployeeDetailView, name='employee_detail'),
   
]

EmployeeInformation/EmpRecord/rest_api/urls.py
from django.urls import path, include 
from .views import DepartmentView, EmployeeView,FilterView
from rest_framework import filters
from rest_framework import routers
# from .views import AuthenticatedView
# from .views import CourseThrottledView
from .views import LoginView, LogoutView
from rest_framework_swagger.views import get_swagger_view

api_router = routers.DefaultRouter(trailing_slash=False)
# api_router.register('student',StudentView)
# api_router.register('course', CourseView)
schema_view = get_swagger_view(title='Employee API: Documentation')

urlpatterns = [ 
    path('', include(api_router.urls)), 
    path('employee_login/', LoginView.as_view()),
    path('employee_logout/', LogoutView.as_view()),
    path('employee/', EmployeeView.as_view(), name="employee_list"),
    path('employee/<int:pk>/', EmployeeView.as_view(), name="employee_detail"),
    path('department/<pk>/', DepartmentView.as_view(), name="department_detail"),
    path('department/', DepartmentView.as_view(), name="department_list"),
    path('api_documentation', schema_view)

]

EmployeeInformation/EmpRecord/urls.py
from django.urls import path 
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from EmpRecord import views


app_name = 'Information'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('employee/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employee/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('create/', views.EmployeeCreateView.as_view(), name='employee_create'),
    path('employee/<int:pk>/update/', views.EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/<pk>/delete/', views.EmployeeDeleteView.as_view(), name='employee_delete'),
    path('departments/', views.DepartmentListView.as_view(), name='department_list'),
    path('departments/<int:pk>/', views.DepartmentDetailView.as_view(), name='department_detail'),
    path('department/', views.DepartmentCreateView.as_view(), name='department_create'),
    path('department/<int:pk>/update/', views.DepartmentUpdateView.as_view(), name='department_update'),
    path('department/<pk>/delete/', views.DepartmentDeleteView.as_view(), name='department_delete'),
   
]

EmployeeInformation/EmployeeInformation/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp_records/', include(('EmpRecord.urls'), namespace='EmpRecord')),
    path('rest_api/', include(('EmpRecord.rest_api.urls', 'EmpRecord_api'),
                                    namespace='rest_api')),
    path('rest_api_viewset/', include(('EmpRecord.rest_api_viewset.urls', 'EmpRecord_api'),
                                    namespace='rest_api_viewset')),                                
    path('rest_api_genericset/', include(('EmpRecord.rest_api_genericset.urls', 'EmpRecord_api'),
                                    namespace='rest_api_genericset')),
    path('postmans/', include(('EmpRecord.Postman_Hardik.urls'))),
    path('hrdik_Cls_bsd_API/', include(('EmpRecord.Hrdik_Cls_bsd_API.urls'))),
    path('hrdik_gnric_API/', include(('EmpRecord.Hrdik_gnric_API.urls'))),                                                              
    path('__debug__/', include(debug_toolbar.urls)),
 ]                               
 

EmployeeInformation/EmpRecord/models.py
from django.db import models
from django.db import models
from django.urls import reverse
# Create your models here.


class Department(models.Model):
    name = models.CharField(max_length=256)
   
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("EmpRecord:detail", args=[str(self.pk)])
    

class Employee(models.Model):
    name = models.CharField(max_length=256)
    designation = models.CharField(max_length=256)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("EmpRecord:detail", args=[str(self.pk)])
    

EmployeeInformation/EmpRecord/Hrdik_Cls_bsd_API/views.py
from django.shortcuts import render, reverse, get_object_or_404
from rest_framework.parsers import JSONParser
from EmpRecord.models import Employee, Department
from django.views.decorators.csrf import csrf_exempt
from django.db.models import F, ExpressionWrapper, DecimalField, Value
from rest_framework.parsers import JSONParser 
from django.http import Http404, HttpResponse, JsonResponse
from .serializerss import EmployeeSerializer
from django.utils.decorators import method_decorator
from rest_framework.views import APIView
from rest_framework.response import Response
from EmpRecord.views import *




class EmployeeAPIView(APIView):
    def get(self, request):
        employee = Employee.objects.all()
        serializers = EmployeeSerializer(employee, many=True)
        return Response(serializers.data, status=200)
    
    def post(self, request):
        data = request.data
        serializers = EmployeeSerializer(data= data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=201)
        return Response(serializers.erros, status=400)
    
class EmployeeDetailAPIView(APIView):
    def get_object(self, id):
        try:
            return Employee.objects.get(id=id)
        except Employee.DoesNotExist as e:
            return None
        
    def get(self, request, id=None):
        instance = self.get_object(id)
        if not instance:
            return Response( {"error": "Given Employee object not found. "}, status= 404)
        serializers = EmployeeSerializer(instance)
        return Response(serializers.data, status=200)
    
    def put(self, request, id=None):
        data = request.data
        instance = self.get_object(id)
        serializers = EmployeeSerializer(instance, data=data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=200)
        return Response(serializers.errors, status=400)
    
    def delete(self, request, id=None):
        instance = self.get_object(id)
        if not instance:
            return Response( {"error": "Given Employee object not found. "}, status= 404)
        instance.delete()
        return HttpResponse()
        

EmployeeInformation/EmpRecord/Hrdik_gnric_API/views.py
from rest_framework import generics, mixins
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from django.db.models import Prefetch
from EmpRecord.models import Employee, Department
from .serializers import DepartmentSerializer, EmployeeSerializer


class EmployeeListView(generics.GenericAPIView, 
                       mixins.ListModelMixin,
                       mixins.CreateModelMixin,
                       mixins.RetrieveModelMixin,
                       mixins.UpdateModelMixin,
                       mixins.DestroyModelMixin):
    
    serializer_class = EmployeeSerializer
    queryset = Employee.objects.all()
    lookup_field = "id"

    def get(self, request, id=None):
        if id:
            return self.retrieve(request, id) 
        else:
            return self.list(request)
    
    def post(self, request):
        return self.create(request)
    
    def perform_create(self, serializer):
        serializer.save(Department=self.request.user)  
    
    def put(self, request, id=None):
        return self.update(request, id)
    
    def delete(self, request, id=None):
        return self.destroy(request, id)
    
class DepartmentListView(generics.GenericAPIView, 
                       mixins.ListModelMixin,
                       mixins.CreateModelMixin,
                       mixins.RetrieveModelMixin,
                       mixins.UpdateModelMixin):
    serializer_class = DepartmentSerializer
    queryset = Department.objects.all()
    lookup_field = 'id'

    def get(self, request):
        if id:
            return self.retrieve(request, id) 
        else:
            return self.list(request)
    
    def post(self, request):
        return self.create(request)
    
    def put(self, request, id=None):
        return self.update(request, id)

EmployeeInformation/EmpRecord/Postman_Hardik/views.py
from django.shortcuts import render, reverse 
from rest_framework.parsers import JSONParser
from EmpRecord.models import Employee, Department
from django.views.decorators.csrf import csrf_exempt
from django.db.models import F, ExpressionWrapper, DecimalField, Value
from rest_framework.parsers import JSONParser 
from django.http import Http404, HttpResponse, JsonResponse
from .serializers import DepartmentSerializer, EmployeeSerializer
from django.utils.decorators import method_decorator



@csrf_exempt
def EmployeeListView(request):
    if request.method == 'GET':
        employee = Employee.objects.all()
        serializer = EmployeeSerializer(employee, many= True)
        return JsonResponse(serializer.data, safe= False)
    
    elif request.method == 'POST':
        Json_parser = JSONParser()
        data = Json_parser.parse(request)
        serializer = EmployeeSerializer(data= data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.erros, status=400)
    

@csrf_exempt
def EmployeeDetailView(request):
    try:
        instance = Employee.objects.all()
    except Employee.DoesNotExist as e:
        return JsonResponse( {"error": "Given employee object not found."}, status=404)

    if request.method == 'GET':
        serializer = EmployeeSerializer(instance)
        return JsonResponse(serializer.data)
    
    elif request.method == "PUT":
        Json_parser = JSONParser()
        data = Json_parser.parse(request.PUT)
        serializer = EmployeeSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=200)
        return JsonResponse(serializer.errors, status=400)

    elif request.method == "DELETE":
       instance.delete()
       return HttpResponse(status=204)
    

EmployeeInformation/EmpRecord/rest_api/views.py
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated 
from rest_framework.response import Response
from rest_framework.response import Response
from rest_framework.decorators import action
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404
from .pagination import CustomPagination
from .serializers import DepartmentSerializer, EmployeeSerializer
from EmpRecord.models import Department, Employee
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.pagination import PageNumberPagination
from django_filters.views import FilterView
from django.contrib.auth import login as django_login, logout as django_logout 
from rest_framework.authtoken.models import Token  
from .serializers import LoginSerializer
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter
from django_filters import FilterSet 
from django_filters.rest_framework import  filters

class LoginView(APIView):
    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data["user"]
        django_login(request, user)
        token, created = Token.objects.get_or_create(user=user)
        return Response({"token": token.key}, status=200)
    

class LogoutView(APIView):
    authentication_classes = (TokenAuthentication, )

    def post(self, request):
        django_logout(request)
        return Response(status=204)
    
class DepartmentView(APIView):
    pagination_class = CustomPagination
    # authentication_classes = [TokenAuthentication]
    # permission_classes = [IsAuthenticated] 
    
    def get(self, request, pk=None):
        user = request.user
        serializers = DepartmentSerializer(data=request.data)

        if pk:
            queryset =  get_object_or_404(Department, pk=pk) 
            serializers = DepartmentSerializer(queryset)
        else:
            queryset = Department.objects.all()
            serializers = DepartmentSerializer(queryset, many=True)
            paginator = self.pagination_class()
            result_page = paginator.paginate_queryset(queryset, request)
            serializers = DepartmentSerializer(result_page, many=True)
            return paginator.get_paginated_response(serializers.data)
        return Response(serializers.data)
         
    def post(self, request):
         serializer = DepartmentSerializer(data=request.data)
         if serializer.is_valid():
             serializer.save()
             return Response(serializer.data, status=status.HTTP_201_CREATED)
         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request):
        serializers = DepartmentSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self,request,pk):
        try:
            department = Department.objects.get(pk=pk)
        except Department.DoesNotExist:
            return Response({"error": "Department not found"}, status=status.HTTP_404_NOT_FOUND)
        department.delete()
        return Response({"message": "Department deleted successfully"}, status=status.HTTP_204_NO_CONTENT)


class EmployeeFilter(FilterSet):
    designation = filters.CharFilter(method='filter_by_designation')
    # min_salary = filters.CharFilter(method="filter_by_min_salary")
    # max_salary = filters.CharFilter(method="filter_by_max_salary")


    class Meta:
        model = Employee
        fields = ('name', 'designation','department')
    
    def filter_by_designation(self, queryset, name, value):
        designation = value.strip().split('-')
        designation = designation.objects.filter(name_in=designation)
        return queryset.filter(designation_in=designation)
    
    # def filter_by_min_salary(self, queryset, name, value):
    #     queryset = queryset.filter(salary_gt=value)
    #     return queryset

    # def filter_by_max_salary(self, queryset, name, value):
    #     queryset = queryset.filter(salary_lt=value)
    #     return queryset
        


class EmployeeView(APIView):
    serializer_class = EmployeeSerializer
    pagination_class = CustomPagination
    # authentication_classes = [TokenAuthentication]
    # permission_classes = [IsAuthenticated] 
    # filter_backends = (DjangoFilterBackend)
    # filter_fields = ( 'name','designation','department')
    filter_backends = (DjangoFilterBackend,OrderingFilter, SearchFilter)
    filter_class = EmployeeFilter
    ordering_fields = ('[designation]')
    ordering = ('name') 
    search_fields = ('name','designation')
    
   
    def get(self, request, pk=None):
        user = request.user
        serializers = EmployeeSerializer(data=request.data)
        if pk:
            instance = Employee.objects.get(pk=pk)
            serializers = EmployeeSerializer(instance)
        else:
            queryset = Employee.objects.all()
            serializers = EmployeeSerializer(queryset, many=True)
            paginator = self.pagination_class()
            result_page = paginator.paginate_queryset(queryset, request)
            serializers = EmployeeSerializer(result_page, many=True)
            return paginator.get_paginated_response(serializers.data)
            
        return Response(serializers.data)

    def get_queryset(self):
        query_set = self.filter_queryset(Employee.objects.all())
        return query_set

    def post(self, request):
        serializers = EmployeeSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request):
        serializers = EmployeeSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self,request,pk):
        try:
            employee = Employee.objects.get(pk=pk)
        except Employee.DoesNotExist:
           return Response({"error": "Employee not found"}, status=status.HTTP_404_NOT_FOUND)
        employee.delete()
        return Response({"message": "Employee deleted successfully"}, status=status.HTTP_204_NO_CONTENT)
        
        
      
        
        


    
   

EmployeeInformation/EmpRecord/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
        <title>Base</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-warning navbar-light">
            <ul class="nav nav-tabs">
              <li class="nav-item active">
                    <a class="nav-link" href="{% url 'EmpRecord:index' %}">Home</a>
                  </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'EmpRecord:employee_list' %}">Employee List</a>
                  </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'EmpRecord:department_list' %}">Department List</a>
                  </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
            </ul>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

EmployeeInformation/EmpRecord/templates/department_create_update_form.html
{% extends 'base.html' %}
{% block body_block %}


    {% if not form.instance.pk %}
    <h1> Department Create</h1>
    {% else %} 
    <h1> Department Update</h1>
    {% endif %}

    <form method="post">
        {% csrf_token %}
            {{ form.as_p }}
        {% if form.instance.pk %}
            <button type="submit">Update department</button>

        {% else %}
        <button type="submit">Save Department</button>
        {% endif %}
    </form>
{% endblock %}

EmployeeInformation/EmpRecord/templates/department_delete.html
{% extends 'base.html' %}

{% block body_block %}
<h1>Delete {{department.name}}?</h1>
<p>Are you sure you want to delete the Department "{{ object.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" class='btn btn-danger' value="Delete">
        <a href="{% url 'EmpRecord:department_delete' pk=department.id  %}"></a>
</form>
{% endblock%}

EmployeeInformation/EmpRecord/templates/department_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the Department Detail page </h1></p>
    <h2>Department details:</h2>
    <p>Name: {{department.name}}</p>
    <p>pk id : {{department.id}}</p>


</div> 
<div class="container">

    <button>
        <a href="{% url 'EmpRecord:department_update' pk=department.id %}">Update</a>
   
    </button>

     <button type="submit"><a href="{% url 'EmpRecord:department_delete' department.id %}">Delete Department</a></button>

     <div>
        <ol>
            {% for department in department_list %}
                <h2><li><a href="{% url 'EmpRecord:department_detail' department.id %}">{{department.name}} </a></li></h2>
                
            {% endfor %}
                
        </ol>
     </div>
</div>
{% endblock %}

EmployeeInformation/EmpRecord/templates/department_list.html
{% extends 'base.html' %}
{% block body_block %}
<h1> Welcome to my WEB !</h1>
    <!-- <ol> 
        {% for department in department_list %}
            <h2><li><a href="{% url 'EmpRecord:department_detail'  department.id%}">{{department.name}}</a></li></h2>

        {% endfor %} 
    </ol> -->
    <div class="container mt-3">
        <li class="list-group-item list-group-item-success"></li>
            <table class="table table-bordered"> 
                <thead>
                    <tr>
                        <th>Sr.No</th>
                        <th>Id</th>
                        <th>Name</th>
                  
                    </tr>
                </thead>
            <tbody> 
                {% for department in department_list %}
                <tr>
                        <td>{{ forloop.counter }}</td> 
                        <td>{{department.id}}</td> 
                        <td><a href="{% url 'EmpRecord:department_detail'  department.id %}">{{department.name}}</a></td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>   
</div> 
   
{% endblock %} 
    

EmployeeInformation/EmpRecord/templates/employee_create_update_form.html
{% extends 'base.html' %}
{% block body_block %}


    {% if not form.instance.pk %}
    <h1> Employee Create</h1>
    {% else %} 
    <h1> Employee Update</h1>
    {% endif %}

    <form method="post">
        {% csrf_token %}
            {{ form.as_p }}
        {% if form.instance.pk %}
            <button type="submit">Update Employee</button>

        {% else %}
        <button type="submit">Save Employee</button>
        {% endif %}
    </form>
{% endblock %}

EmployeeInformation/EmpRecord/templates/employee_delete.html
{% extends 'base.html' %}

{% block body_block %}
<h1>Delete {{employee.name}}?</h1>
<p>Are you sure you want to delete the employee"{{ object.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" class='btn btn-danger' value="Delete">
        <a href="{% url 'EmpRecord:employee_delete' pk=employee.id  %}"></a>
</form>
{% endblock%}

EmployeeInformation/EmpRecord/templates/employee_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the Employee Detail page </h1></p>
    <h2>Employee details:</h2>
    <p>Name: {{employee.name}}</p>
    <p>Designation: {{employee.designation}}</p>
    <p>Department: {{employee.department}}</p>

    <div class="container">

            
        <button>
            <a href="{% url 'EmpRecord:employee_update' pk=employee.id %}">Update</a>
        </button>
    
         <button type="submit"><a href="{% url 'EmpRecord:employee_delete' employee.id %}">Delete Employee</a></button>
    </div>
    
        
{% endblock %}

EmployeeInformation/EmpRecord/templates/employee_list.html
{% extends 'base.html' %}
{% block body_block %}
<h1> Welcome to List of Employees!</h1>
    <!-- <ol> 
        {% for employee in employee_list %}
            <h2><li><a href="{% url 'EmpRecord:employee_detail'  employee.id%}">{{employee.name}}</a></li></h2>
    
        {% endfor %}
    </ol>  --> 
    <div class="container mt-3">
        <table class="table table-bordered"> 
            <thead>
                <tr>
                  <th>Sr.No</th>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Designation</th>
                  <th>Department</th>
                 </tr>
            </thead>
            <tbody> 
              {% for employee in employee_list %}
              <tr>
                    <td>{{ forloop.counter }}</td> 
                    <td>{{employee.id}}</td> 
                    <td><a href="{% url 'EmpRecord:employee_detail' pk=employee.id %}">{{employee.name}}</a></td>
                    <td>{{employee.designation}}</td>
                    <td>{{employee.department}}</td>
              </tr>
              {% endfor %}
            </tbody>
        </table>   
</div> 

{% endblock %}

EmployeeInformation/EmpRecord/templates/filters.html
{% extends "base.html" %}

{% block content %}
    <form method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.name }} - ${{ obj.price }}<br />
    {% endfor %}
{% endblock %}

EmployeeInformation/EmpRecord/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron "> 
        <h1>Welcome to my Area! </h1>
    </div>
{% endblock %}